apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: memcached-reserve
  name: memcached-reserve
  namespace: hotel-res
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: memcached-reserve
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
        sidecar.istio.io/statsInclusionPrefixes: cluster.outbound,cluster_manager,listener_manager,http_mixer_filter,tcp_mixer_filter,server,cluster.xds-grp,listener,connection_manager
        sidecar.istio.io/statsInclusionRegexps: http.*
      creationTimestamp: null
      labels:
        io.kompose.service: memcached-reserve
    spec:
      nodeSelector:
        kubernetes.io/hostname: im-hp-10
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
      containers:
        - env:
            - name: MEMCACHED_CACHE_SIZE
              value: "128"
            - name: MEMCACHED_THREADS
              value: "2"
          image: memcached
          name: hotel-reserv-reservation-mmc
          ports:
            - containerPort: 11211
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 1000m
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: memcached-reserve
  name: memcached-reserve
  namespace: hotel-res
spec:
  ports:
    - name: "memcached-reserve"
      port: 11211
      targetPort: 11211
  selector:
    io.kompose.service: memcached-reserve
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: mongodb-reservation
  name: mongodb-reservation
  namespace: hotel-res
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongodb-reservation
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
        sidecar.istio.io/statsInclusionPrefixes: cluster.outbound,cluster_manager,listener_manager,http_mixer_filter,tcp_mixer_filter,server,cluster.xds-grp,listener,connection_manager
        sidecar.istio.io/statsInclusionRegexps: http.*
      creationTimestamp: null
      labels:
        io.kompose.service: mongodb-reservation
    spec:
      nodeSelector:
        kubernetes.io/hostname: im-hp-10
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
      containers:
        - image: mongo:4.4.6
          name: hotel-reserv-reservation-mongo
          ports:
            - containerPort: 27017
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 1000m
          volumeMounts:
            - mountPath: /data/db
              name: reservation
      hostname: reservation-db
      restartPolicy: Always
      volumes:
        - name: reservation
          persistentVolumeClaim:
            claimName: reservation-pvc
status: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: mongodb-reservation
  name: mongodb-reservation
  namespace: hotel-res
spec:
  ports:
    - name: "mongodb-reservation"
      port: 27017
      targetPort: 27017
  selector:
    io.kompose.service: mongodb-reservation
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: reservation
  name: reservation
  namespace: hotel-res
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: reservation
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
        sidecar.istio.io/statsInclusionPrefixes: cluster.outbound,cluster_manager,listener_manager,http_mixer_filter,tcp_mixer_filter,server,cluster.xds-grp,listener,connection_manager
        sidecar.istio.io/statsInclusionRegexps: http.*
      creationTimestamp: null
      labels:
        io.kompose.service: reservation
    spec:
      containers:
        - command:
            - /go/bin/reservation
          image: malla8848/hotel-reservation:k8sdns-v1
          name: hotel-reserv-reservation
          ports:
            - containerPort: 8087
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 1000m
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: reservation-pv
spec:
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - im-hp-10
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  storageClassName: reservation-storage
  hostPath:
    path: /data/volumes/reservation-pv   # Where all the hard drives are mounted
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: reservation-pvc
  namespace: hotel-res
spec:
  volumeName: reservation-pv
  accessModes:
    - ReadWriteOnce
  storageClassName: reservation-storage
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: reservation
  name: reservation
  namespace: hotel-res
spec:
  ports:
    - name: "8087"
      port: 8087
      targetPort: 8087
  selector:
    io.kompose.service: reservation
status:
  loadBalancer: {}
